apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-operator-karmada-resource-interpreter
  namespace: karmada-system
  labels:
    app: rabbitmq-operator-karmada-resource-interpreter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-operator-karmada-resource-interpreter
  template:
    metadata:
      labels:
        app: rabbitmq-operator-karmada-resource-interpreter
    spec:
      serviceAccountName: rabbitmq-operator-karmada-resource-interpreter
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
      containers:
        - name: rabbitmq-operator-karmada-resource-interpreter
          image: swr.ap-southeast-1.myhuaweicloud.com/karmada/rabbitmq-operator-karmada-resource-interpreter:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/rabbitmq-operator-karmada-resource-interpreter
            - --kubeconfig=/etc/kubeconfig
            - --bind-address=0.0.0.0
            - --secure-port=8445
            - --cert-dir=/var/serving-cert
            - --v=4
          ports:
            - containerPort: 8445
          volumeMounts:
            - name: kubeconfig
              subPath: kubeconfig
              mountPath: /etc/kubeconfig
            - name: cert
              mountPath: /var/serving-cert
              readOnly: true
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8445
              scheme: HTTPS
      volumes:
        - name: kubeconfig
          secret:
            secretName: kubeconfig
        - name: cert
          secret:
            secretName: webhook-cert
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-operator-karmada-resource-interpreter
  namespace: karmada-system
spec:
  selector:
    app: rabbitmq-operator-karmada-resource-interpreter
  ports:
    - port: 443
      targetPort: 8445
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq-operator-karmada-resource-interpreter
  namespace: karmada-system
